var _sampleQuery = 
	"SELECT EMP.SAL, EMP.ENAME, 7, 'TEST'\n" +
	"FROM EMP, DEPT\n";

var _sampleQuery_next = 
	"SELECT EMP.SAL, EMP.ENAME, 7, 'TEST', (SELECT DEPT.DNAME FROM DEPT) SQ1\n" +
	"FROM EMP, DEPT, (SELECT TAB1.COL1 FROM TAB1 WHERE TAB1.COL2 = 'THIS') SQ2\n" +
	"WHERE EMP.DNAME = DEPT.DNAME AND EMP.TEST1 = DEPT.TEST1 OR( EMP.TEST2 = DEPT.TEST2 AND EMP.TEST3 = EMP.TEST3)";